[package]
name = "FPlot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.35.0"
winit = "0.26.0"
raw-window-handle = "0.4.2"
gpu-allocator = "0.14.0"

[build-dependencies]
shaderc = "0.7.3"